# coding: utf-8

import Pyjo.Test


class NoseTest(Pyjo.Test.NoseTest):
    script = __file__
    srcdir = '../..'


class UnitTest(Pyjo.Test.UnitTest):
    script = __file__


if __name__ == '__main__':

    from Pyjo.Test import *  # @UnusedWildImport

    import Pyjo.URL

    # Simple
    url = Pyjo.URL.new('HtTp://Example.Com')
    is_ok(url.scheme, 'HtTp', 'right scheme')
    is_ok(url.protocol, 'http', 'right protocol')
    is_ok(url.host, 'Example.Com', 'right host')
    is_ok(url.ihost, 'example.com', 'right internationalized host')
    is_ok(url.authority, 'example.com', 'right authority')
    is_ok(str(url), 'http://example.com', 'right format')

    # Advanced
    url = Pyjo.URL.new('https://sri:foobar@example.com:8080/x/index.html?monkey=biz&foo=1#/!%?@3')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'https', 'right scheme')
    is_ok(url.protocol, 'https', 'right protocol')
    is_ok(url.userinfo, 'sri:foobar', 'right userinfo')
    is_ok(url.host, 'example.com', 'right host')
    is_ok(url.port, 8080, 'right port')
    is_ok(url.authority, 'sri:foobar@example.com:8080', 'right authority')
    is_ok(str(url.path), '/x/index.html', 'right path')
    is_ok(str(url.query), 'monkey=biz&foo=1', 'right query')
    is_ok(url.path_query, '/x/index.html?monkey=biz&foo=1', 'right path and query')
    is_ok(url.fragment, '/!%?@3', 'right fragment')
    is_ok(str(url), 'https://sri:foobar@example.com:8080/x/index.html?monkey=biz&foo=1#/!%?@3', 'right format')
    url.path = '/index.xml'
    is_ok(str(url), 'https://sri:foobar@example.com:8080/index.xml?monkey=biz&foo=1#/!%?@3', 'right format')

    # Advanced userinfo and fragment roundtrip
    url = Pyjo.URL.new('ws://AZaz09-._~!$&\'()*+,;=:@localhost#AZaz09-._~!$&\'()*+,;=%:@/?')
    is_ok(url.scheme, 'ws', 'right scheme')
    is_ok(url.userinfo, 'AZaz09-._~!$&\'()*+,;=:', 'right userinfo')
    is_ok(url.host, 'localhost', 'right host')
    is_ok(url.fragment, 'AZaz09-._~!$&\'()*+,;=%:@/?', 'right fragment')
    is_ok(str(url), 'ws://AZaz09-._~!$&\'()*+,;=:@localhost#AZaz09-._~!$&\'()*+,;=%:@/?', 'right format')

    # Parameters
    url = Pyjo.URL.new('http://sri:foobar@example.com:8080?_monkey=biz%3B&_monkey=23#23')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, 'sri:foobar', 'right userinfo')
    is_ok(url.host, 'example.com', 'right host')
    is_ok(url.port, 8080, 'right port')
    is_ok(str(url.path), '', 'no path')
    is_ok(str(url.query), '_monkey=biz%3B&_monkey=23', 'right query')
    is_deeply_ok(url.query.to_dict(), {'_monkey': ['biz;', '23']}, 'right structure')
    is_ok(url.fragment, '23', 'right fragment')
    is_ok(str(url), 'http://sri:foobar@example.com:8080?_monkey=biz%3B&_monkey=23#23', 'right format')
    url.query = [('monkey', 'foo')]
    is_ok(str(url), 'http://sri:foobar@example.com:8080?monkey=foo#23', 'right format')
    url.query.merge(('monkey', 'bar'),)
    is_ok(str(url), 'http://sri:foobar@example.com:8080?monkey=bar#23', 'right format')
    url.query.append(('foo', 'bar'),)
    is_ok(str(url), 'http://sri:foobar@example.com:8080?monkey=bar&foo=bar#23', 'right format')
    url.query = 'foo'
    is_ok(str(url), 'http://sri:foobar@example.com:8080?foo#23', 'right format')
    url.query = 'foo=bar'
    is_ok(str(url), 'http://sri:foobar@example.com:8080?foo=bar#23', 'right format')
    url.query.merge(foo=None)
    is_ok(str(url), 'http://sri:foobar@example.com:8080#23', 'right format')
    url.query.append(('foo', 23), ('bar', 24), ('baz', 25))
    is_ok(str(url), 'http://sri:foobar@example.com:8080?foo=23&bar=24&baz=25#23', 'right format')
    url.query.merge(foo=26, bar=None, baz=None)
    is_ok(str(url), 'http://sri:foobar@example.com:8080?foo=26#23', 'right format')
    url.query = Pyjo.Parameters.new('a=1&b=2')
    is_ok(str(url), 'http://sri:foobar@example.com:8080?a=1&b=2#23', 'right format')
    url.query = {'c': 3}
    is_ok(str(url), 'http://sri:foobar@example.com:8080?c=3#23', 'right format')

    # Query string
    url = Pyjo.URL.new('wss://sri:foobar@example.com:8080?_monkeybiz%3B&_monkey;23#23')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'wss', 'right scheme')
    is_ok(url.userinfo, 'sri:foobar', 'right userinfo')
    is_ok(url.host, 'example.com', 'right host')
    is_ok(url.port, 8080, 'right port')
    is_ok(str(url.path), '', 'no path')
    is_ok(str(url.query), '_monkeybiz%3B&_monkey;23', 'right query')
    is_deeply_ok(url.query.params, [('_monkeybiz;', ''), ('_monkey;23', '')], 'right structure')
    is_ok(str(url.query), '_monkeybiz%3B=&_monkey%3B23=', 'right query')
    is_ok(url.fragment, '23', 'right fragment')
    is_ok(str(url), 'wss://sri:foobar@example.com:8080?_monkeybiz%3B=&_monkey%3B23=#23', 'right format')
    url = Pyjo.URL.new('https://example.com/0?0#0')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'https', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'example.com', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(url.host_port, 'example.com', 'right host and port')
    is_ok(str(url.path), '/0', 'no path')
    is_ok(str(url.query), '0', 'right query')
    is_ok(url.fragment, '0', 'right fragment')
    is_ok(str(url), 'https://example.com/0?0#0', 'right format')

    # No authority
    url = Pyjo.URL.new('DATA:image/png;base64,helloworld123')
    is_ok(url.scheme, 'DATA', 'right scheme')
    is_ok(url.protocol, 'data', 'right protocol')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, None, 'no host')
    is_ok(url.port, None, 'no port')
    is_ok(url.authority, None, 'no authority')
    is_ok(str(url.path), 'image/png;base64,helloworld123', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'data:image/png;base64,helloworld123', 'right format')
    url = url.clone()
    is_ok(url.scheme, 'DATA', 'right scheme')
    is_ok(url.protocol, 'data', 'right protocol')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, None, 'no host')
    is_ok(url.port, None, 'no port')
    is_ok(url.authority, None, 'no authority')
    is_ok(str(url.path), 'image/png;base64,helloworld123', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'data:image/png;base64,helloworld123', 'right format')
    url = Pyjo.URL.new().parse('mailto:sri@example.com')
    is_ok(url.scheme, 'mailto', 'right scheme')
    is_ok(url.protocol, 'mailto', 'right protocol')
    is_ok(str(url.path), 'sri@example.com', 'right path')
    is_ok(str(url), 'mailto:sri@example.com', 'right format')
    url = Pyjo.URL.new().parse('foo:/test/123?foo=bar#baz')
    is_ok(url.scheme, 'foo', 'right scheme')
    is_ok(url.protocol, 'foo', 'right protocol')
    is_ok(str(url.path), '/test/123', 'right path')
    is_ok(str(url.query), 'foo=bar', 'right query')
    is_ok(url.fragment, 'baz', 'right fragment')
    is_ok(str(url), 'foo:/test/123?foo=bar#baz', 'right format')
    is_ok(str(url.set(scheme='Bar')), 'bar:/test/123?foo=bar#baz', 'right format')
    is_ok(url.scheme, 'Bar', 'right scheme')
    is_ok(url.protocol, 'bar', 'right protocol')
    is_ok(url.host, None, 'no host')
    is_ok(url.authority, None, 'no authority')
    is_ok(str(url.path), '/test/123', 'right path')
    is_ok(str(url.query), 'foo=bar', 'right query')
    is_ok(url.fragment, 'baz', 'right fragment')
    is_ok(str(url), 'bar:/test/123?foo=bar#baz', 'right format')
    url = Pyjo.URL.new().parse('file:///foo/bar')
    is_ok(url.scheme, 'file', 'right scheme')
    is_ok(url.protocol, 'file', 'right protocol')
    is_ok(str(url.path), '/foo/bar', 'right path')
    is_ok(str(url), 'file:///foo/bar', 'right format')
    url = url.clone()
    is_ok(url.scheme, 'file', 'right scheme')
    is_ok(url.protocol, 'file', 'right protocol')
    is_ok(str(url.path), '/foo/bar', 'right path')
    is_ok(str(url), 'file:///foo/bar', 'right format')
    url = Pyjo.URL.new().parse('foo:0')
    is_ok(url.scheme, 'foo', 'right scheme')
    is_ok(url.protocol, 'foo', 'right protocol')
    is_ok(str(url.path), '0', 'right path')
    is_ok(str(url), 'foo:0', 'right format')

    # Relative
    url = Pyjo.URL.new('foo?foo=bar#23')
    is_ok(url.path_query, 'foo?foo=bar', 'right path and query')
    ok(not url.is_abs, 'is not absolute')
    is_ok(str(url), 'foo?foo=bar#23', 'right relative version')
    url = Pyjo.URL.new('/foo?foo=bar#23')
    is_ok(url.path_query, '/foo?foo=bar', 'right path and query')
    ok(not url.is_abs, 'is not absolute')
    is_ok(str(url), '/foo?foo=bar#23', 'right relative version')

    # Relative without scheme
    url = Pyjo.URL.new('//localhost/23/')
    ok(not url.is_abs, 'is not absolute')
    is_ok(url.scheme, None, 'no scheme')
    is_ok(url.protocol, '', 'no protocol')
    is_ok(url.host, 'localhost', 'right host')
    is_ok(str(url.path), '/23/', 'right path')
    is_ok(str(url), '//localhost/23/', 'right relative version')
    is_ok(str(url.to_abs(Pyjo.URL.new('http://'))), 'http://localhost/23/', 'right absolute version')
    is_ok(str(url.to_abs(Pyjo.URL.new('https://'))), 'https://localhost/23/', 'right absolute version')
    is_ok(str(url.to_abs(Pyjo.URL.new('http://mojolicio.us'))), 'http://localhost/23/', 'right absolute version')
    is_ok(str(url.to_abs(Pyjo.URL.new('http://mojolicio.us:8080'))), 'http://localhost/23/', 'right absolute version')
    url = Pyjo.URL.new('///bar/23/')
    ok(not url.is_abs, 'is not absolute')
    is_ok(url.host, '', 'no host')
    is_ok(str(url.path), '/bar/23/', 'right path')
    is_ok(str(url), '///bar/23/', 'right relative version')
    url = Pyjo.URL.new('////bar//23/')
    ok(not url.is_abs, 'is not absolute')
    is_ok(url.host, '', 'no host')
    is_ok(str(url.path), '//bar//23/', 'right path')
    is_ok(str(url), '////bar//23/', 'right relative version')

    # Relative path
    url = Pyjo.URL.new('http://example.com/foo/?foo=bar#23')
    url.path = 'bar'
    is_ok(str(url), 'http://example.com/foo/bar?foo=bar#23', 'right path')
    url = Pyjo.URL.new('http://example.com?foo=bar#23')
    url.path = 'bar'
    is_ok(str(url), 'http://example.com/bar?foo=bar#23', 'right path')
    url = Pyjo.URL.new('http://example.com/foo?foo=bar#23')
    url.path = 'bar'
    is_ok(str(url), 'http://example.com/bar?foo=bar#23', 'right path')
    url = Pyjo.URL.new('http://example.com/foo/bar?foo=bar#23')
    url.path = 'yada/baz'
    is_ok(str(url), 'http://example.com/foo/yada/baz?foo=bar#23', 'right path')
    url = Pyjo.URL.new('http://example.com/foo/bar?foo=bar#23')
    url.path = '../baz'
    is_ok(str(url), 'http://example.com/foo/../baz?foo=bar#23', 'right path')
    url.path.canonicalize()
    is_ok(str(url), 'http://example.com/baz?foo=bar#23', 'right absolute path')

    # Absolute (base without trailing slash)
    url = Pyjo.URL.new('/foo?foo=bar#23')
    url.base.parse('http://example.com/bar')
    ok(not url.is_abs, 'not absolute')
    is_ok(str(url.to_abs()), 'http://example.com/foo?foo=bar#23', 'right absolute version')
    url = Pyjo.URL.new('../cages/birds.gif')
    url.base.parse('http://www.aviary.com/products/intro.html')
    ok(not url.is_abs, 'not absolute')
    is_ok(str(url.to_abs()), 'http://www.aviary.com/cages/birds.gif', 'right absolute version')
    url = Pyjo.URL.new('.././cages/./birds.gif')
    url.base.parse('http://www.aviary.com/./products/./intro.html')
    ok(not url.is_abs, 'not absolute')
    is_ok(str(url.to_abs()), 'http://www.aviary.com/cages/birds.gif', 'right absolute version')

    # Absolute with path
    url = Pyjo.URL.new('../foo?foo=bar#23')
    url.base.parse('http://example.com/bar/baz/')
    ok(not url.is_abs, 'not absolute')
    is_ok(str(url.to_abs()), 'http://example.com/bar/foo?foo=bar#23', 'right absolute version')
    is_ok(str(url.to_abs().base), 'http://example.com/bar/baz/', 'right base')

    # Clone (advanced)
    url = Pyjo.URL.new('ws://sri:foobar@example.com:8080/test/index.html?monkey=biz&foo=1#23')
    clone = url.clone()
    ok(clone.is_abs, 'is absolute')
    is_ok(clone.scheme, 'ws', 'right scheme')
    is_ok(clone.userinfo, 'sri:foobar', 'right userinfo')
    is_ok(clone.host, 'example.com', 'right host')
    is_ok(clone.port, 8080, 'right port')
    is_ok(str(clone.path), '/test/index.html', 'right path')
    is_ok(str(clone.query), 'monkey=biz&foo=1', 'right query')
    is_ok(clone.fragment, '23', 'right fragment')
    is_ok(str(clone), 'ws://sri:foobar@example.com:8080/test/index.html?monkey=biz&foo=1#23', 'right format')
    clone.path = '/index.xml'
    is_ok(str(clone), 'ws://sri:foobar@example.com:8080/index.xml?monkey=biz&foo=1#23', 'right format')

    # Clone (with base)
    url = Pyjo.URL.new('/test/index.html')
    url.base.parse('http://127.0.0.1')
    is_ok(str(url), '/test/index.html', 'right format')
    clone = url.clone()
    is_ok(str(url), '/test/index.html', 'right format')
    ok(not clone.is_abs, 'not absolute')
    is_ok(clone.scheme, None, 'no scheme')
    is_ok(clone.host, None, 'no host')
    is_ok(clone.base.scheme, 'http', 'right base scheme')
    is_ok(clone.base.host, '127.0.0.1', 'right base host')
    is_ok(str(clone.path), '/test/index.html', 'right path')
    is_ok(str(clone.to_abs()), 'http://127.0.0.1/test/index.html', 'right absolute version')

    # Clone (with base path)
    url = Pyjo.URL.new('test/index.html')
    url.base.parse('http://127.0.0.1/foo/')
    is_ok(str(url), 'test/index.html', 'right format')
    clone = url.clone()
    is_ok(str(url), 'test/index.html', 'right format')
    ok(not clone.is_abs, 'not absolute')
    is_ok(clone.scheme, None, 'no scheme')
    is_ok(clone.host, None, 'no host')
    is_ok(clone.base.scheme, 'http', 'right base scheme')
    is_ok(clone.base.host, '127.0.0.1', 'right base host')
    is_ok(str(clone.path), 'test/index.html', 'right path')
    is_ok(str(clone.to_abs()), 'http://127.0.0.1/foo/test/index.html', 'right absolute version')

    # IPv6
    url = Pyjo.URL.new('wss://[::1]:3000/')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'wss', 'right scheme')
    is_ok(url.host, '[::1]', 'right host')
    is_ok(url.port, 3000, 'right port')
    is_ok(str(url.path), '/', 'right path')
    is_ok(str(url), 'wss://[::1]:3000/', 'right format')

    # IDNA
    url = Pyjo.URL.new(u'http://bücher.ch:3000/foo')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.host, u'bücher.ch', 'right host')
    is_ok(url.ihost, 'xn--bcher-kva.ch', 'right internationalized host')
    is_ok(url.port, 3000, 'right port')
    is_ok(url.host_port, 'xn--bcher-kva.ch:3000', 'right host and port')
    is_ok(str(url.path), '/foo', 'right path')
    is_ok(url.path_query, '/foo', 'right path and query')
    is_ok(str(url), 'http://xn--bcher-kva.ch:3000/foo', 'right format')
    url = Pyjo.URL.new(u'http://bücher.bücher.ch:3000/foo')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.host, u'bücher.bücher.ch', 'right host')
    is_ok(url.ihost, 'xn--bcher-kva.xn--bcher-kva.ch', 'right internationalized host')
    is_ok(url.port, 3000, 'right port')
    is_ok(str(url.path), '/foo', 'right path')
    is_ok(str(url), 'http://xn--bcher-kva.xn--bcher-kva.ch:3000/foo', 'right format')
    url = Pyjo.URL.new(u'http://bücher.bücher.bücher.ch:3000/foo')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.host, u'bücher.bücher.bücher.ch', 'right host')
    is_ok(url.ihost, 'xn--bcher-kva.xn--bcher-kva.xn--bcher-kva.ch', 'right internationalized host')
    is_ok(url.port, 3000, 'right port')
    is_ok(str(url.path), '/foo', 'right path')
    is_ok(str(url), 'http://xn--bcher-kva.xn--bcher-kva.xn--bcher-kva.ch:3000/foo', 'right format')

    # IDNA (escaped userinfo and host)
    url = Pyjo.URL.new('https://foo:b%C3%A4r@kr%C3%A4ih.com:3000')
    is_ok(url.host, u"kr\xe4ih.com", 'right host')
    is_ok(url.ihost, 'xn--krih-moa.com', 'right internationalized host')
    is_ok(url.port, 3000, 'right port')
    is_ok(str(url), 'https://foo:b%C3%A4r@xn--krih-moa.com:3000', 'right format')

    # IDNA (snowman)
    url = Pyjo.URL.new(u'http://☃.net/')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.host, u'☃.net', 'right host')
    is_ok(url.ihost, 'xn--n3h.net', 'right internationalized host')
    is_ok(str(url.path), '/', 'right path')
    is_ok(str(url), 'http://xn--n3h.net/', 'right format')

    # IRI/IDNA
    url = Pyjo.URL.new(u'http://☃.net/♥/?q=♥☃')
    is_ok(url.path.parts[0], u'♥', 'right path part')
    is_ok(str(url.path), '/%E2%99%A5/', 'right path')
    is_ok(str(url.query), 'q=%E2%99%A5%E2%98%83', 'right query')
    is_ok(url.query.param('q'), u'♥☃', 'right query value')
    url = Pyjo.URL.new(u'http://☃.Net/♥/♥/?♥=☃')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.host, u'☃.Net', 'right host')
    is_ok(url.ihost, 'xn--n3h.net', 'right internationalized host')
    is_ok(str(url.path), '/%E2%99%A5/%E2%99%A5/', 'right path')
    is_deeply_ok(url.path.parts, [u'♥', u'♥'], 'right structure')
    is_ok(url.query.param(u'♥'), u'☃', 'right query value')
    is_ok(str(url), 'http://xn--n3h.net/%E2%99%A5/%E2%99%A5/?%E2%99%A5=%E2%98%83', 'right format')
    url = Pyjo.URL.new('http://xn--n3h.net/%E2%99%A5/%E2%99%A5/?%E2%99%A5=%E2%98%83')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.host, 'xn--n3h.net', 'right host')
    is_ok(url.ihost, 'xn--n3h.net', 'right internationalized host')
    is_ok(str(url.path), '/%E2%99%A5/%E2%99%A5/', 'right path')
    is_deeply_ok(url.path.parts, [u'♥', u'♥'], 'right structure')
    is_ok(url.query.param(u'♥'), u'☃', 'right query value')
    is_ok(str(url), 'http://xn--n3h.net/%E2%99%A5/%E2%99%A5/?%E2%99%A5=%E2%98%83', 'right format')

    # Already absolute
    url = Pyjo.URL.new('http://foo.com/')
    is_ok(str(url.to_abs()), 'http://foo.com/', 'right absolute version')

    # Empty path elements
    url = Pyjo.URL.new('http://example.com/foo//bar/23/')
    ok(url.is_abs, 'is absolute')
    is_ok(str(url.path), '/foo//bar/23/', 'right path')
    is_ok(str(url), 'http://example.com/foo//bar/23/', 'right format')
    url = Pyjo.URL.new('http://example.com//foo//bar/23/')
    ok(url.is_abs, 'is absolute')
    is_ok(str(url.path), '//foo//bar/23/', 'right path')
    is_ok(str(url), 'http://example.com//foo//bar/23/', 'right format')
    url = Pyjo.URL.new('http://example.com/foo///bar/23/')
    ok(url.is_abs, 'is absolute')
    is_ok(str(url.path), '/foo///bar/23/', 'right path')
    is_ok(str(url), 'http://example.com/foo///bar/23/', 'right format')

    # Merge relative path
    url = Pyjo.URL.new('http://foo.bar/baz?yada')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/baz?yada', 'right absolute URL')
    url = Pyjo.URL.new('zzz?Zzz').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz?yada', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/zzz', 'right path')
    is_ok(str(url.query), 'Zzz', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/zzz?Zzz', 'right absolute URL')

    # Merge relative path with directory
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada', 'right absolute URL')
    url = Pyjo.URL.new('zzz?Zzz').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/zzz', 'right path')
    is_ok(str(url.query), 'Zzz', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/baz/zzz?Zzz', 'right absolute URL')

    # Merge absolute path
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada', 'right absolute URL')
    url = Pyjo.URL.new('/zzz?Zzz').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/zzz', 'right path')
    is_ok(str(url.query), 'Zzz', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/zzz?Zzz', 'right absolute URL')

    # Merge absolute path without query
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada', 'right absolute URL')
    url = Pyjo.URL.new('/zzz').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/zzz', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/zzz', 'right absolute URL')

    # Merge absolute path with fragment
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada#test1')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, 'test1', 'right fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada#test1', 'right absolute URL')
    url = Pyjo.URL.new('/zzz#test2').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada#test1', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/zzz', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, 'test2', 'right fragment')
    is_ok(str(url), 'http://foo.bar/zzz#test2', 'right absolute URL')

    # Merge relative path with fragment
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada#test1')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, 'test1', 'right fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada#test1', 'right absolute URL')
    url = Pyjo.URL.new('zzz#test2').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada#test1', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/zzz', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, 'test2', 'right fragment')
    is_ok(str(url), 'http://foo.bar/baz/zzz#test2', 'right absolute URL')

    # Merge absolute path without fragment
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada#test1')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, 'test1', 'right fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada#test1', 'right absolute URL')
    url = Pyjo.URL.new('/zzz').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada#test1', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/zzz', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/zzz', 'right absolute URL')

    # Merge relative path without fragment
    url = Pyjo.URL.new('http://foo.bar/baz/index.html?yada#test1')
    is_ok(str(url.base), '', 'no base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/index.html', 'right path')
    is_ok(str(url.query), 'yada', 'right query')
    is_ok(url.fragment, 'test1', 'right fragment')
    is_ok(str(url), 'http://foo.bar/baz/index.html?yada#test1', 'right absolute URL')
    url = Pyjo.URL.new('zzz').set(base=url).to_abs()
    is_ok(str(url.base), 'http://foo.bar/baz/index.html?yada#test1', 'right base')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'foo.bar', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/baz/zzz', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, None, 'no fragment')
    is_ok(str(url), 'http://foo.bar/baz/zzz', 'right absolute URL')

    # Hosts
    url = Pyjo.URL.new('http://mojolicio.us')
    is_ok(url.host, 'mojolicio.us', 'right host')
    url = Pyjo.URL.new('http://[::1]')
    is_ok(url.host, '[::1]', 'right host')
    url = Pyjo.URL.new('http://127.0.0.1')
    is_ok(url.host, '127.0.0.1', 'right host')
    url = Pyjo.URL.new('http://0::127.0.0.1')
    is_ok(url.host, '0::127.0.0.1', 'right host')
    url = Pyjo.URL.new('http://[0::127.0.0.1]')
    is_ok(url.host, '[0::127.0.0.1]', 'right host')
    url = Pyjo.URL.new('http://mojolicio.us:3000')
    is_ok(url.host, 'mojolicio.us', 'right host')
    url = Pyjo.URL.new('http://[::1]:3000')
    is_ok(url.host, '[::1]', 'right host')
    url = Pyjo.URL.new('http://127.0.0.1:3000')
    is_ok(url.host, '127.0.0.1', 'right host')
    url = Pyjo.URL.new('http://0::127.0.0.1:3000')
    is_ok(url.host, '0::127.0.0.1', 'right host')
    url = Pyjo.URL.new('http://[0::127.0.0.1]:3000')
    is_ok(url.host, '[0::127.0.0.1]', 'right host')
    url = Pyjo.URL.new('http://foo.1.1.1.1.de/')
    is_ok(url.host, 'foo.1.1.1.1.de', 'right host')
    url = Pyjo.URL.new('http://1.1.1.1.1.1/')
    is_ok(url.host, '1.1.1.1.1.1', 'right host')

    # Heavily escaped path and empty fragment
    url = Pyjo.URL.new('http://example.com/mojo%2Fg%2B%2B-4%2E2_4%2E2%2E3-2ubuntu7_i386%2Edeb#')
    ok(url.is_abs, 'is absolute')
    is_ok(url.scheme, 'http', 'right scheme')
    is_ok(url.userinfo, None, 'no userinfo')
    is_ok(url.host, 'example.com', 'right host')
    is_ok(url.port, None, 'no port')
    is_ok(str(url.path), '/mojo%2Fg%2B%2B-4%2E2_4%2E2%2E3-2ubuntu7_i386%2Edeb', 'right path')
    is_ok(str(url.query), '', 'no query')
    is_ok(url.fragment, '', 'right fragment')
    is_ok(str(url), 'http://example.com/mojo%2Fg%2B%2B-4%2E2_4%2E2%2E3-2ubuntu7_i386%2Edeb#', 'right format')
    url.path.canonicalize()
    is_ok(str(url), 'http://example.com/mojo/g++-4.2_4.2.3-2ubuntu7_i386.deb#', 'right format')

    # "%" in path
    url = Pyjo.URL.new('http://mojolicio.us/100%_fun')
    is_ok(url.path.parts[0], '100%_fun', 'right part')
    is_ok(str(url.path), '/100%25_fun', 'right path')
    is_ok(str(url), 'http://mojolicio.us/100%25_fun', 'right format')
    url = Pyjo.URL.new('http://mojolicio.us/100%fun')
    is_ok(url.path.parts[0], '100%fun', 'right part')
    is_ok(str(url.path), '/100%25fun', 'right path')
    is_ok(str(url), 'http://mojolicio.us/100%25fun', 'right format')
    url = Pyjo.URL.new('http://mojolicio.us/100%25_fun')
    is_ok(url.path.parts[0], '100%_fun', 'right part')
    is_ok(str(url.path), '/100%25_fun', 'right path')
    is_ok(str(url), 'http://mojolicio.us/100%25_fun', 'right format')

    # No charset
    url = Pyjo.URL.new()
    url.path.charset = None
    url.query.charset = None
    url.parse('HTTP://FOO.BAR/%E4/?%E5=%E4')
    is_ok(url.scheme, 'HTTP', 'right scheme')
    is_ok(url.protocol, 'http', 'right protocol')
    is_ok(url.host, 'FOO.BAR', 'right host')
    is_ok(url.ihost, 'foo.bar', 'right internationalized host')
    is_ok(str(url.path), '/%E4/', 'right path')
    is_deeply_ok(url.path.parts, [b"\xe4"], 'right structure')
    ok(url.path.leading_slash, 'has leading slash')
    ok(url.path.trailing_slash, 'has trailing slash')
    is_ok(str(url.query), '%E5=%E4', 'right query')
    is_ok(url.query.param(b"\xe5"), b"\xe4", 'right value')
    is_ok(str(url), 'http://foo.bar/%E4/?%E5=%E4', 'right format')

    # Resolve RFC 1808 examples
    base = Pyjo.URL.new('http://a/b/c/d?q#f')
    url = Pyjo.URL.new('g')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g', 'right absolute version')
    url = Pyjo.URL.new('./g')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g', 'right absolute version')
    url = Pyjo.URL.new('g/')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g/', 'right absolute version')
    url = Pyjo.URL.new('//g')
    is_ok(str(url.to_abs(base)), 'http://g', 'right absolute version')
    url = Pyjo.URL.new('?y')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/d?y', 'right absolute version')
    url = Pyjo.URL.new('g?y')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g?y', 'right absolute version')
    url = Pyjo.URL.new('g?y/./x')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g?y/./x', 'right absolute version')
    url = Pyjo.URL.new('#s')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/d?q#s', 'right absolute version')
    url = Pyjo.URL.new('g#s')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g#s', 'right absolute version')
    url = Pyjo.URL.new('g#s/./x')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g#s/./x', 'right absolute version')
    url = Pyjo.URL.new('g?y#s')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/g?y#s', 'right absolute version')
    url = Pyjo.URL.new('.')
    is_ok(str(url.to_abs(base)), 'http://a/b/c', 'right absolute version')
    url = Pyjo.URL.new('./')
    is_ok(str(url.to_abs(base)), 'http://a/b/c/', 'right absolute version')
    url = Pyjo.URL.new('..')
    is_ok(str(url.to_abs(base)), 'http://a/b', 'right absolute version')
    url = Pyjo.URL.new('../')
    is_ok(str(url.to_abs(base)), 'http://a/b/', 'right absolute version')
    url = Pyjo.URL.new('../g')
    is_ok(str(url.to_abs(base)), 'http://a/b/g', 'right absolute version')
    url = Pyjo.URL.new('../..')
    is_ok(str(url.to_abs(base)), 'http://a/', 'right absolute version')
    url = Pyjo.URL.new('../../')
    is_ok(str(url.to_abs(base)), 'http://a/', 'right absolute version')
    url = Pyjo.URL.new('../../g')
    is_ok(str(url.to_abs(base)), 'http://a/g', 'right absolute version')

    done_testing()
