language: python
env:
  global:
    - PYTHONIOENCODING='utf-8'
matrix:
  include:
  - python: "2.7"
    env: PACKAGES=''
  - python: "2.7"
    env: PACKAGES='' PYTHONIOENCODING='ascii'
  - python: "3.4"
    env: PACKAGES=''
  - python: "pypy"
    env: PACKAGES=''
  - python: "pypy3"
    env: PACKAGES=''
before_install:
  - sudo apt-get update -qq
install:
  - # pip install -q flake8
  - # flake8 --config .flake8 .
  - if [ -n "$PACKAGES" ]; then pip install $PACKAGES; fi
script:
  - python test.py
