language: python
matrix:
  include:
  - python: "2.7"
    env: PYTHONIOENCODING='utf-8'
  - python: "2.7"
    env: PYTHONIOENCODING=''
  - python: "3.4"
    env: PYTHONIOENCODING='utf-8'
  - python: "3.4"
    env: PYTHONIOENCODING=''
  - python: "pypy"
    env: PYTHONIOENCODING='utf-8'
  - python: "pypy3"
    env: PYTHONIOENCODING='utf-8'
before_install:
  - sudo apt-get update -qq
install:
  - # pip install -q flake8
  - # flake8 --config .flake8 .
script:
  - python test.py
